import { configureStore } from '@reduxjs/toolkit';
import orders from './ordersSlice';
import products from './productsSlice';
import ui from './uiSlice';
import settings from './settingsSlice';
import management from './managementSlice';
import auth from './authSlice';
export const store = configureStore({ reducer: { orders, products, ui, settings, management, auth } });
export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
